<a href="https://colab.research.google.com/github/emincingoz/Machine_Learning_Collection/blob/main/CTGAN_GeneratingSyntheticData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install ctgan

Collecting ctgan
  Downloading ctgan-0.5.1-py2.py3-none-any.whl (24 kB)
Requirement already satisfied: torch<2,>=1.8.0 in /usr/local/lib/python3.7/dist-packages (from ctgan) (1.11.0+cu113)
Requirement already satisfied: torchvision<1,>=0.9.0 in /usr/local/lib/python3.7/dist-packages (from ctgan) (0.12.0+cu113)
Collecting rdt<0.7,>=0.6.2
  Downloading rdt-0.6.4-py2.py3-none-any.whl (45 kB)
     |████████████████████████████████| 45 kB 2.7 MB/s
Requirement already satisfied: numpy<2,>=1.20.0 in /usr/local/lib/python3.7/dist-packages (from ctgan) (1.21.6)
Requirement already satisfied: pandas<2,>=1.1.3 in /usr/local/lib/python3.7/dist-packages (from ctgan) (1.3.5)
Requirement already satisfied: packaging<22,>=20 in /usr/local/lib/python3.7/dist-packages (from ctgan) (21.3)
Requirement already satisfied: scikit-learn<2,>=0.24 in /usr/local/lib/python3.7/dist-packages (from ctgan) (1.0.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging<22,>=20->ctgan) (3.0.9)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas<2,>=1.1.3->ctgan) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas<2,>=1.1.3->ctgan) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas<2,>=1.1.3->ctgan) (1.15.0)
Collecting pyyaml<6,>=5.4.1
  Downloading PyYAML-5.4.1-cp37-cp37m-manylinux1_x86_64.whl (636 kB)
     |████████████████████████████████| 636 kB 12.0 MB/s
Collecting psutil<6,>=5.7
  Downloading psutil-5.9.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (280 kB)
     |████████████████████████████████| 280 kB 48.0 MB/s
Collecting scipy<1.8,>=1.5.4
  Downloading scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
     |████████████████████████████████| 38.1 MB 1.3 MB/s
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn<2,>=0.24->ctgan) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn<2,>=0.24->ctgan) (3.1.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from torch<2,>=1.8.0->ctgan) (4.2.0)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from torchvision<1,>=0.9.0->ctgan) (2.23.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.7/dist-packages (from torchvision<1,>=0.9.0->ctgan) (7.1.2)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->torchvision<1,>=0.9.0->ctgan) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->torchvision<1,>=0.9.0->ctgan) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->torchvision<1,>=0.9.0->ctgan) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->torchvision<1,>=0.9.0->ctgan) (2021.10.8)
Installing collected packages: scipy, pyyaml, psutil, rdt, ctgan
  Attempting uninstall: scipy
    Found existing installation: scipy 1.4.1
    Uninstalling scipy-1.4.1:
      Successfully uninstalled scipy-1.4.1
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
  Attempting uninstall: psutil
    Found existing installation: psutil 5.4.8
    Uninstalling psutil-5.4.8:
      Successfully uninstalled psutil-5.4.8
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
Successfully installed ctgan-0.5.1 psutil-5.9.0 pyyaml-5.4.1 rdt-0.6.4 scipy-1.7.3

In [9]:
from google.colab import drive
drive.mount("/gdrive")
%cd /gdrive

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive

In [23]:
from ctgan import CTGANSynthesizer
from ctgan import load_demo
import pandas as pd

#data = load_demo()

# Names of the columns that are discrete
discrete_columns = [
    'BolgeCografya',
    'BolgeTipi',
    'AraziBoyutu',
    'AracYogunluk',
    'AracOrtMobility',
    'KameraliSistem',
    'DataRateDurum',
    'ReliabilityDurum',
    'LatencyDurum',
    'SensorYogunluk',
    'SensorVeriIletim',
    #'Standart'
]

data = pd.read_csv("MyDrive/NextGCT-IRG/dataFeatureSet.csv", header = None)

data.columns = discrete_columns

labels = pd.read_csv("MyDrive/NextGCT-IRG/dataCLassLabels.csv", header = None)
labels.columns = ['Standart']

dataset = pd.concat([data, labels], axis = 1)

ctgan = CTGANSynthesizer(epochs=10)
ctgan.fit(dataset, discrete_columns)

# Synthetic copy
samples = ctgan.sample(1000)

/usr/local/lib/python3.7/dist-packages/sklearn/mixture/_base.py:146: ConvergenceWarning: Number of distinct clusters (3) found smaller than n_clusters (10). Possibly due to duplicate points in X.
  .fit(X)
/usr/local/lib/python3.7/dist-packages/ctgan/data_transformer.py:111: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[column_name] = data[column_name].to_numpy().flatten()

In [24]:
samples

,BolgeCografya,BolgeTipi,AraziBoyutu,AracYogunluk,AracOrtMobility,KameraliSistem,DataRateDurum,ReliabilityDurum,LatencyDurum,SensorYogunluk,SensorVeriIletim,Standart
0,2,1,1,1,2,2,2,2,2,1,1,3
1,1,2,2,2,2,1,2,1,2,2,2,2
2,2,1,1,2,1,1,2,2,2,1,2,3
3,1,2,2,2,2,2,2,2,1,1,2,3
4,2,1,2,1,1,2,1,1,2,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
995,1,1,2,1,2,2,1,1,2,2,2,2
996,2,2,2,2,2,2,2,2,2,2,2,3
997,2,1,2,1,1,2,1,2,1,2,2,1
998,1,2,1,1,2,2,1,2,1,2,2,1
999,2,2,2,1,2,1,2,1,1,2,2,1

In [26]:
samples = ctgan.sample(30000)
samples

,BolgeCografya,BolgeTipi,AraziBoyutu,AracYogunluk,AracOrtMobility,KameraliSistem,DataRateDurum,ReliabilityDurum,LatencyDurum,SensorYogunluk,SensorVeriIletim,Standart
0,1,1,2,1,2,1,2,1,2,1,2,1
1,2,1,2,1,1,2,1,1,1,2,2,1
2,1,1,2,1,2,1,1,1,2,1,1,1
3,2,1,1,1,1,1,2,1,2,1,2,1
4,2,1,1,1,1,1,1,1,1,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
29995,2,1,1,2,1,2,1,2,2,2,2,3
29996,1,1,2,1,1,2,2,1,2,2,2,1
29997,1,2,2,2,2,1,2,1,1,1,2,2
29998,1,2,2,2,2,2,2,2,2,2,2,2
29999,1,2,2,1,2,1,2,2,1,1,2,3